class BackendService {
  static Future<List> getSuggestions(String query) async {
//    await Future.delayed(Duration(seconds: 0));

    List<String> listaRetorno = listaDeCursos();

    return listaRetorno
        .where((f) => f.startsWith(query.toUpperCase()))
        .toList();
  }

  static List<String> listaDeCursos() {
    List<String> listaRetorno = new List();
    listaRetorno.add('ADMINISTRAÇÃO');
    listaRetorno.add('ARQUITETURA E URBANISMO');
    listaRetorno.add('BIBLIOTECONOMIA');
    listaRetorno.add('CIÊNCIAS BIOLÓGICAS');
    listaRetorno.add('CIÊNCIAS CONTÁBEIS');
    listaRetorno.add('CIÊNCIA DA COMPUTAÇÃO');
    listaRetorno.add('CIÊNCIAS ECONÔMICAS');
    listaRetorno.add('CIÊNCIAS SOCIAIS');
    listaRetorno.add('COMUNICAÇÃO SOCIAL');
    listaRetorno.add('DIREITO');
    listaRetorno.add('EDUCAÇÃO FÍSICA');
    listaRetorno.add('ENFERMAGEM');
    listaRetorno.add('ENGENHARIA CIVIL');
    listaRetorno.add('ENGENHARIA DE COMPUTAÇÃO');
    listaRetorno.add('ENGENHARIA DE MATERIAIS');
    listaRetorno.add('ENGENHARIA DE PRODUÇÃO');
    listaRetorno.add('ENGENHARIA ELÉTRICA');
    listaRetorno.add('ENGENHARIA MECÂNICA');
    listaRetorno.add('ENGENHARIA QUÍMICA');
    listaRetorno.add('ENGENHARIA TÊXTIL');
    listaRetorno.add('ESTATÍSTICA');
    listaRetorno.add('FARMÁCIA');
    listaRetorno.add('FILOSOFIA');
    listaRetorno.add('FÍSICA');
    listaRetorno.add('FISIOTERAPIA');
    listaRetorno.add('GEOGRAFIA');
    listaRetorno.add('GEOLOGIA');
    listaRetorno.add('HISTÓRIA');
    listaRetorno.add('LETRAS');
    listaRetorno.add('MATEMÁTICA');
    listaRetorno.add('MEDICINA');
    listaRetorno.add('MÚSICA');
    listaRetorno.add('ODONTOLOGIA');
    listaRetorno.add('PEDAGOGIA');
    listaRetorno.add('PSICOLOGIA');
    listaRetorno.add('QUÍMICA');
    listaRetorno.add('SERVIÇO SOCIAL');
    listaRetorno.add('TURISMO');
    listaRetorno.add('ZOOTECNIA');
    listaRetorno.add('AQUICULTURA');
    listaRetorno.add('ECOLOGIA');
    listaRetorno.add('BIOMEDICINA');
    listaRetorno.add('ARTES VISUAIS');
    listaRetorno.add('ENGENHARIA DE ALIMENTOS');
    listaRetorno.add('TEATRO');
    listaRetorno.add('GESTÃO HOSPITALAR');
    listaRetorno.add('GESTÃO PÚBLICA');
    listaRetorno.add('ENGENHARIA DE PETRÓLEO');
    listaRetorno.add('ENGENHARIA DE AQUICULTURA');
    listaRetorno.add('ENGENHARIA AGRONÔMICA');
    listaRetorno.add('GEOFÍSICA');
    listaRetorno.add('QUÍMICA DO PETRÓLEO');
    listaRetorno.add('ZOOTECNIA');
    listaRetorno.add('CIÊNCIAS ATUARIAIS');
    listaRetorno.add('DESIGN');
    listaRetorno.add('SISTEMAS DE INFORMAÇÃO');
    listaRetorno.add('SAÚDE COLETIVA');
    listaRetorno.add('DANÇA');
    listaRetorno.add('FONOAUDIOLOGIA');
    listaRetorno.add('ENGENHARIA FLORESTAL');
    listaRetorno.add('NUTRIÇÃO');
    listaRetorno.add('CIÊNCIAS E TECNOLOGIA');
    listaRetorno.add('GESTÃO DE POLÍTICAS PÚBLICAS');
    listaRetorno.add('ENGENHARIA DE SOFTWARE');
    listaRetorno.add('LETRAS -');
    listaRetorno.add('ENGENHARIA DE TELECOMUNICAÇÕES');
    listaRetorno.add('ENGENHARIA AMBIENTAL');
    listaRetorno.add('ENGENHARIA BIOMÉDICA');
    listaRetorno.add('MATEMÁTICA');
    listaRetorno.add('ENGENHARIA MECATRÔNICA');
    listaRetorno.add('TECNOLOGIA DA INFORMAÇÃO');
    listaRetorno.add('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS');
    listaRetorno.add('GESTÃO DE COOPERATIVAS');
    listaRetorno.add('METEOROLOGIA');
    listaRetorno.add('CIÊNCIAS SOCIAIS');
    listaRetorno.add('MEDICINA');
    listaRetorno.add('CIÊNCIAS BIOLÓGICAS');
    listaRetorno.add('EDUCAÇÃO FÍSICA');
    listaRetorno.add('FILOSOFIA');
    listaRetorno.add('FÍSICA');
    listaRetorno.add('GEOGRAFIA');
    listaRetorno.add('HISTÓRIA');
    listaRetorno.add('LETRAS');
    listaRetorno.add('MATEMÁTICA');
    listaRetorno.add('MÚSICA');
    listaRetorno.add('QUÍMICA');
    listaRetorno.add('CIÊNCIAS SOCIAIS');
    listaRetorno.add('COMUNICAÇÃO SOCIAL- PUBLICIDADE E PROPAGANDA');
    listaRetorno.add('JORNALISMO');
    listaRetorno.add('LETRAS - FRANCÊS');
    listaRetorno.add('LETRAS - INGLÊS');
    listaRetorno.add('LETRAS- LÍNGUA ESPANHOLA E LITERATURAS');
    listaRetorno.add('LETRAS - LÍNGUA PORTUGUESA');
    listaRetorno.add('LETRAS - LÍNGUA PORTUGUESA E LIBRAS');
    listaRetorno.add('LETRAS - LÍNGUA ESPANHOLA');
    listaRetorno.add('LETRAS - LÍNGUA PORTUGUESA');
    listaRetorno.add('LETRAS - PORTUGUÊS E INGLÊS');
    listaRetorno.add('COMUNICAÇÃO SOCIAL - AUDIOVISUAL');
    return listaRetorno;
  }

  static Map<String, String> cursosComId() {
    Map<String, String> curso = Map();
    curso['ADMINISTRAÇÃO'] = '2000004.0';
    curso['ARQUITETURA E URBANISMO'] = '2000005.0';
    curso['BIBLIOTECONOMIA'] = '2000006.0';
    curso['CIÊNCIAS BIOLÓGICAS'] = '2000009.0';
    curso['CIÊNCIAS CONTÁBEIS'] = '2000012.0';
    curso['CIÊNCIA DA COMPUTAÇÃO'] = '2000013.0';
    curso['CIÊNCIAS ECONÔMICAS'] = '2000014.0';
    curso['CIÊNCIAS SOCIAIS'] = '2000015.0';
    curso['COMUNICAÇÃO SOCIAL'] = '2000016.0';
    curso['DIREITO'] = '2000018.0';
    curso['ENFERMAGEM'] = '2000023.0';
    curso['ENGENHARIA CIVIL'] = '2000025.0';
    curso['ENGENHARIA DE COMPUTAÇÃO'] = '2000026.0';
    curso['ENGENHARIA DE MATERIAIS'] = '2000027.0';
    curso['ENGENHARIA DE PRODUÇÃO'] = '2000029.0';
    curso['ENGENHARIA ELÉTRICA'] = '2000030.0';
    curso['ENGENHARIA MECÂNICA'] = '2000031.0';
    curso['ENGENHARIA QUÍMICA'] = '2000032.0';
    curso['ENGENHARIA TÊXTIL'] = '2000033.0';
    curso['ESTATÍSTICA'] = '2000034.0';
    curso['FARMÁCIA'] = '2000039.0';
    curso['FILOSOFIA'] = '2000040.0';
    curso['FÍSICA'] = '2000041.0';
    curso['GEOGRAFIA'] = '2000044.0';
    curso['GEOLOGIA'] = '2000045.0';
    curso['HISTÓRIA'] = '2000047.0';
    curso['LETRAS'] = '2000053.0';
    curso['MATEMÁTICA'] = '2000054.0';
    curso['MEDICINA'] = '2000056.0';
    curso['MÚSICA'] = '2000057.0';
    curso['NUTRIÇÃO'] = '2000058.0';
    curso['ODONTOLOGIA'] = '2000059.0';
    curso['PEDAGOGIA'] = '2000063.0';
    curso['PSICOLOGIA'] = '2000066.0';
    curso['QUÍMICA'] = '2000067.0';
    curso['SERVIÇO SOCIAL'] = '2000068.0';
    curso['TURISMO'] = '2000069.0';
    curso['ZOOTECNIA'] = '2000072.0';
    curso['AQUICULTURA'] = '2000114.0';
    curso['ECOLOGIA'] = '2000121.0';
    curso['BIOMEDICINA'] = '2000122.0';
    curso['ARTES VISUAIS'] = '2000123.0';
    curso['ENGENHARIA DE ALIMENTOS'] = '2000150.0';
    curso['TEATRO'] = '2000158.0';
    curso['GESTÃO HOSPITALAR'] = '2000159.0';
    curso['GESTÃO PÚBLICA'] = '2000160.0';
    curso['ENGENHARIA DE PETRÓLEO'] = '2071220.0';
    curso['ENGENHARIA DE AQUICULTURA'] = '2576623.0';
    curso['ENGENHARIA AGRONÔMICA'] = '2576632.0';
    curso['GEOFÍSICA'] = '2936390.0';
    curso['QUÍMICA DO PETRÓLEO'] = '3156200.0';
    curso['ZOOTECNIA'] = '6358080.0';
    curso['CIÊNCIAS ATUARIAIS'] = '6633741.0';
    curso['DESIGN'] = '6992521.0';
    curso['SISTEMAS DE INFORMAÇÃO'] = '7191770.0';
    curso['SAÚDE COLETIVA'] = '7252420.0';
    curso['DANÇA'] = '7264330.0';
    curso['FONOAUDIOLOGIA'] = '7410980.0';
    curso['ENGENHARIA FLORESTAL'] = '8068230.0';
    curso['CIÊNCIAS E TECNOLOGIA'] = '10320810.0';
    curso['FISIOTERAPIA'] = '10345860.0';
    curso['GESTÃO DE POLÍTICAS PÚBLICAS'] = '10426760.0';
    curso['ENGENHARIA DE SOFTWARE'] = '17848940.0';
    curso['LETRAS -'] = '84767886.0';
    curso['ENGENHARIA DE TELECOMUNICAÇÕES'] = '85322080.0';
    curso['ENGENHARIA AMBIENTAL'] = '85322571.0';
    curso['ENGENHARIA BIOMÉDICA'] = '85341136.0';
    curso['MATEMÁTICA'] = '85436489.0';
    curso['ENGENHARIA MECATRÔNICA'] = '85437055.0';
    curso['TECNOLOGIA DA INFORMAÇÃO'] = '92127264.0';
    curso['ANÁLISE E DESENVOLVIMENTO DE SISTEMAS'] = '94598200.0';
    curso['GESTÃO DE COOPERATIVAS'] = '96726786.0';
    curso['METEOROLOGIA'] = '101644626.0';
    curso['CIÊNCIAS SOCIAIS'] = '102191189.0';
    curso['MEDICINA'] = '104831949.0';
    curso['CIÊNCIAS BIOLÓGICAS'] = '111635035.0';
    curso['CIÊNCIAS SOCIAIS'] = '111635038.0';
    curso['EDUCAÇÃO FÍSICA'] = '111635041.0';
    curso['FILOSOFIA'] = '111635047.0';
    curso['FÍSICA'] = '111635050.0';
    curso['GEOGRAFIA'] = '111635053.0';
    curso['HISTÓRIA'] = '111635060.0';
    curso['LETRAS'] = '111635063.0';
    curso['MATEMÁTICA'] = '111635066.0';
    curso['MÚSICA'] = '111635069.0';
    curso['QUÍMICA'] = '111635075.0';
    curso['CIÊNCIAS SOCIAIS'] = '118589263.0';
    curso['COMUNICAÇÃO SOCIAL- PUBLICIDADE E PROPAGANDA'] = '118834827.0';
    curso['JORNALISMO'] = '118835329.0';
    curso['LETRAS - FRANCÊS'] = '118836561.0';
    curso['LETRAS - INGLÊS'] = '118840295.0';
    curso['LETRAS- LÍNGUA ESPANHOLA E LITERATURAS'] = '118880834.0';
    curso['LETRAS - LÍNGUA PORTUGUESA'] = '118881115.0';
    curso['LETRAS - LÍNGUA PORTUGUESA E LIBRAS'] = '118921874.0';
    curso['LETRAS - LÍNGUA ESPANHOLA'] = '118922026.0';
    curso['LETRAS - PORTUGUÊS E INGLÊS'] = '133175344.0';
    curso['COMUNICAÇÃO SOCIAL - AUDIOVISUAL'] = '119512361.0';

    return curso;
  }
}
